export const red = 'red'
export const blue = 'blue'
export const green = 'green'
export const white = 'white'
export const grey = 'grey'
export const navBar = 'rgb(36, 36, 36)'
export const background = 'rgb(42, 42, 42)'